#pragma once

#include "Greis/CustomType/BandDelayCustomType.h"
#include "Greis/CustomType/ClkOffsCustomType.h"
#include "Greis/CustomType/ExtSpecDataCustomType.h"
#include "Greis/CustomType/GPSAlm1CustomType.h"
#include "Greis/CustomType/GPSEphemeris1CustomType.h"
#include "Greis/CustomType/GpsEphReqDataCustomType.h"
#include "Greis/CustomType/GpsNavData1CustomType.h"
#include "Greis/CustomType/GpsRawNavData1CustomType.h"
#include "Greis/CustomType/HeaderCustomType.h"
#include "Greis/CustomType/IonoParams1CustomType.h"
#include "Greis/CustomType/SlotRecCustomType.h"
#include "Greis/CustomType/SmoothCustomType.h"
#include "Greis/CustomType/SpecDataCustomType.h"
#include "Greis/CustomType/SvData0CustomType.h"
#include "Greis/CustomType/SvData1CustomType.h"
#include "Greis/CustomType/SvData2CustomType.h"
#include "Greis/CustomType/SvDelayCustomType.h"
#include "Greis/CustomType/UtcOffsCustomType.h"

